[workspace]
resolver = "3"
members = ["rush-env", "rush-say", "rush-var"]

[workspace.package]
version = "0.1.1"
edition = "2024"
description = "A modern, configuration-driven Zsh environment generator"
authors = ["BppleMan"]
license = "Apache-2.0"
repository = "https://github.com/BppleMan/rush-env"

[workspace.dependencies]
serde = { version = "1.0.228", default-features = false }
toml = { version = "0.9.8", default-features = false }
thiserror = { version = "2.0.17", default-features = false }
color-eyre = { version = "0.6.5", default-features = false }
clap = { version = "4.5.53", default-features = false }
inquire = { version = "0.9.1", default-features = false }
include_dir = { version = "0.7.4", default-features = false }
tokio = { version = "1.48.0", default-features = false }
derive_more = { version = "2.1.0", default-features = false }
which = { version = "8.0.0" }
tracing = { version = "0.1.43", default-features = false }
tracing-subscriber = { version = "0.3.22", default-features = false }
tracing-appender = { version = "0.2.4", default-features = false }
indexmap = { version = "2.12.1", default-features = false }
