[package]
name = "rush-var"
description = "Expand shell-style variables like $FOO and ${BAR:-default} recursively"
version = "0.1.1"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
