"====================================================
"=                   基础配置                       =
"====================================================

set nocompatible                                    " 去除vi一致性
set encoding=UTF-8

let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

"====================================================
"=                   插件列表                       =
"====================================================
call plug#begin('~/plugged')

Plug 'terryma/vim-multiple-cursors'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'preservim/nerdtree'
            \ | Plug 'xuyuanp/nerdtree-git-plugin'
            \ | Plug 'ryanoasis/vim-devicons'
Plug 'easymotion/vim-easymotion'                    " 智能跳转到单词
Plug 'luochen1990/rainbow'                          " 彩色括号
Plug 'mhinz/vim-startify'
Plug 'christoomey/vim-tmux-navigator'

" Plug 'sjl/vitality.vim'                           " (Vit)ality 是一个插件，可以让 (V)im 与 (i)Term 2 和 (t)mux 完美配合。

" Plug 'neoclide/coc.nvim', {'branch': 'release'}     " coc.vim
" Plug 'Shougo/neco-vim'
" Plug 'neoclide/coc-neco'
Plug 'neoclide/jsonc.vim'

Plug 'sbdchd/neoformat'

Plug 'lukas-reineke/indent-blankline.nvim'          " 彩色的indent对齐线

Plug 'sainnhe/everforest'
Plug 'catppuccin/vim', { 'as': 'catppuccin' }
Plug 'rose-pine/neovim', { 'as': 'rose-pine' }
"Plug 'tjdevries/colorbuddy.nvim'
"Plug 'BppleMan/monokai-soda.vim'
"Plug 'tanvirtin/monokai.nvim'

Plug 'rust-lang/rust.vim'
call plug#end()

"====================================================
"=                     常规设置                     =
"====================================================
syntax on
set number                                          "开启行号
set encoding=utf-8
set t_Co=256
set textwidth=120
set relativenumber                                  " 显示当前行行号,其它行则显示相对行号
set showmatch                                       " 高亮匹配的括号{[()]}
"set spell spelllang=en_us                          " 英语拼写检查
set autoread                                        " 自动读取文件在磁盘上的改动
filetype plugin indent on
set tabstop=4                                       " show existing tab with 4 spaces width
set shiftwidth=4                                    " when indenting with '>', use 4 spaces width
set expandtab                                       " On pressing tab, insert 4 spaces
set cursorline                                      " 高亮当前行
set cursorcolumn                                    " 高亮当前列
set wildmenu                                        " visual autocomplete for command menu
set hlsearch                                        " 搜索高亮匹配
"set foldenable                                     " 启用折叠
"set foldmethod=indent                              " 根据缩进折叠
set clipboard=unnamed                               " 默认使用系统剪贴板寄存器
set timeout                                         " 设置命令序列直接间隔的等待时间
set timeoutlen=200
set ttimeout
set ttimeoutlen=200
set bs=2                                            " 设置退格键可以删除空行
set guifont=JetBrainsMonoNerdFontComplete-Light:h18
let mapleader=","

"====================================================
"=                     插件设置                     =
"====================================================

" -------------------monokai-soda--------------------
let g:enable_bold_font=1
let g:enable_italic_font=1

if (has("nvim"))
    "For Neovim 0.1.3 and 0.1.4 < https://github.com/neovim/neovim/pull/2198 >
    let $NVIM_TUI_ENABLE_TRUE_COLOR=1
endif

"For Neovim > 0.1.5 and Vim > patch 7.4.1799 < https://github.com/vim/vim/commit/61be73bb0f965a895bfb064ea3e55476ac175162 >
"Based on Vim patch 7.4.1770 (`guicolors` option) < https://github.com/vim/vim/commit/8a633e3427b47286869aa4b96f2bfc1fe65b25cd >
" < https://github.com/neovim/neovim/wiki/Following-HEAD#20160511 >
if (has("termguicolors"))
    set termguicolors
endif

let g:everforest_background = 'hard'  " 可选：soft | medium | hard
let g:everforest_enable_italic = 1
let g:everforest_disable_italic_comment = 0
colorscheme everforest

"colorscheme catppuccin_mocha
"colorscheme rose-pine
"colorscheme monokai-soda

" -------------------vim-airline--------------------
let g:airline_theme='molokai'
let g:airline_powerline_fonts = 1


" -------------------nerdtree-----------------------
" nnoremap <leader>f :NERDTreeFind<CR>              " 定位到当前文件
let NERDTreeIgnore=['\.meta$']
let NERDTreeShowHidden=1
nnoremap <C-t> :NERDTreeMirror<CR>
" nerdtree-git-plugin
let g:NERDTreeGitStatusShowIgnored = 1

"let g:NERDTreeGitStatusUseNerdFonts = 1
let g:NERDTreeGitStatusShowClean = 1

" vim-tmux-navigator
let g:tmux_navigator_save_on_switch = 2

" ------------------vim-rainbow---------------------
let g:rainbow_active = 1

" -------------------EasyMotion---------------------
" Disable default mappings
let g:EasyMotion_do_mapping = 0
let g:EasyMotion_smartcase = 1                      " Turn on case-insensitive feature

map f <Plug>(easymotion-bd-f)
nmap f <Plug>(easymotion-overwin-f2)

map gl <Plug>(easymotion-bd-jk)
nmap gl <Plug>(easymotion-overwin-line)

map  W <Plug>(easymotion-bd-w)
nmap W <Plug>(easymotion-overwin-w)

map  / <Plug>(easymotion-sn)
nmap / <Plug>(easymotion-tn)

" These `n` & `N` mappings are options. You do not have to map `n` & `N` to EasyMotion.
" Without these mappings, `n` & `N` works fine. (These mappings just provide
" different highlight method and have some other features )
map  n <Plug>(easymotion-next)
map  N <Plug>(easymotion-prev)

" -------------------vim-startify---------------------
let g:startify_custom_header =
            \ startify#pad(split(system('figlet -f isometric1 Hello World'), '\n'))

" -----------------------rust-------------------------
let g:rustfmt_autosave=1

" ---------------------coc.nvim-----------------------
" if !has("ide")
"     set signcolumn=yes
"     nnoremap CC :CocConfig<CR>
"     function! SetupCommandAbbrs(from, to)
"         exec 'cnoreabbrev <expr> '.a:from
"                     \ .' ((getcmdtype() ==# ":" && getcmdline() ==# "'.a:from.'")'
"                     \ .'? ("'.a:to.'") : ("'.a:from.'"))'
"     endfunction
" 
"     call SetupCommandAbbrs('C', 'CocConfig')
" 
"     " Use <Tab> and <S-Tab> to navigate the completion list:
"     inoremap <silent><expr> <TAB>
"         \ coc#pum#visible() ? coc#pum#next(1) :
"         \ CheckBackspace() ? "\<Tab>" :
"         \ coc#refresh()
"     inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"
" 
"     " Make <CR> to accept selected completion item or notify coc.nvim to format
"     " <C-g>u breaks current undo, please make your own choice.
"     inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
"                                 \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
" 
"     " use <Shift-space>for trigger completion
"     inoremap <silent><expr> <S-Space> coc#refresh()
" 
"     function! CheckBackspace() abort
"         let col = col('.') - 1
"         return !col || getline('.')[col - 1]  =~# '\s'
"     endfunction
" 
"     " Use `[g` and `]g` to navigate diagnostics
"     " Use `:CocDiagnostics` to get all diagnostics of current buffer in location list.
"     nmap <silent> [g <Plug>(coc-diagnostic-prev)
"     nmap <silent> ]g <Plug>(coc-diagnostic-next)
" 
"     " GoTo code navigation.
"     nmap <silent> gd <Plug>(coc-definition)
"     nmap <silent> gy <Plug>(coc-type-definition)
"     nmap <silent> gi <Plug>(coc-implementation)
"     nmap <silent> gr <Plug>(coc-references)
" 
"     " Use K to show documentation in preview window.
"     nnoremap <silent> K :call ShowDocumentation()<CR>
" 
"     function! ShowDocumentation()
"       if CocAction('hasProvider', 'hover')
"         call CocActionAsync('doHover')
"       else
"         call feedkeys('K', 'in')
"       endif
"     endfunction
" 
"     " Highlight the symbol and its references when holding the cursor.
"     autocmd CursorHold * silent call CocActionAsync('highlight')
" 
"     " Formatting selected code.
"     xmap <leader>f  <Plug>(coc-format-selected)
"     nmap <leader>f  <Plug>(coc-format-selected)
" 
"     " Remap keys for applying codeAction to the current buffer.
"     nmap <leader>ac  <Plug>(coc-codeaction)
"     " Apply AutoFix to problem on the current line.
"     nmap <leader>qf  <Plug>(coc-fix-current)
" 
"     " Run the Code Lens action on the current line.
"     nmap <leader>cl  <Plug>(coc-codelens-action)
" 
"     " Add `:OR` command for organize imports of the current buffer.
"     command! -nargs=0 OR   :call     CocActionAsync('runCommand', 'editor.action.organizeImport')
" endif

"====================================================
"=                     键位映射                     =
"====================================================
nnoremap j gj
nnoremap k gk
" move to beginning/end of line
noremap B ^
noremap E $
" $/^ doesn't do anything
nnoremap $ <nop>
nnoremap ^ <nop>
inoremap jk <esc>
nnoremap <leader>v :tabnew ~/.vimrc<CR>
nnoremap <leader>z :tabnew ~/.zshrc<CR>
nnoremap <leader>sv :source ~/.vimrc<CR>
nnoremap <leader>sn :source ~/.config/nvim/init.vim<CR>

" 使用:set nohlsearch会导致当前的会话永久取消搜索高亮
" 使用:noh只会在取消此次搜索的高亮,下次搜索会自动启用hl
" 因此把Ctrl-C映射到[:noh回车],就能通过快捷键取消当前搜索的hl
nnoremap <nowait><silent> <C-c> :noh<CR>

nnoremap x "_x
nnoremap X "_X
nnoremap d "_d
nnoremap dd "_dd
nnoremap D "_D
vnoremap d "_d
vnoremap dd "_dd

"====================================================
"=                   自动命令                       =
"====================================================
let g:gutentags_enabled=0                           " 关掉烦人的gutentags: ctags job failed, returned: 1
if $TERM_PROGRAM =~ "iTerm"
    let &t_SI = "\<Esc>]50;CursorShape=1\x7"        " Vertical bar in insert mode
    let &t_EI = "\<Esc>]50;CursorShape=0\x7"        " Block in normal mode
endif

if has("autocmd")
    augroup manual
        autocmd!
        " 自动跳到上次打开的光标位置
        autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

        " Start NERDTree and put the cursor back in the other window.
        autocmd VimEnter * NERDTreeMirror | wincmd p

        " Exit Vim if NERDTree is the only window remaining in the only tab.
        autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree()
                    \ | call system('printf "\e[5 q" > $TTY')
                    \ | quit
                    \ | endif
        " Close the tab if NERDTree is the only window remaining in it.
        autocmd BufEnter * if winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree()
                    \ | call system('printf "\e[5 q" > $TTY')
                    \ | quit
                    \ | endif
        " Open the existing NERDTree on each new tab.
        " autocmd BufWinEnter * if getcmdwintype() == '' | silent NERDTreeMirror | endif

        autocmd VimLeave * call system('printf "\e[5 q" > $TTY')
    augroup END

    augroup filetype
        autocmd!
        autocmd BufRead,BufNewFile *.swift set ft=swift
        autocmd FileType json syntax match Comment +\/\/.\+$+
    augroup END

    augroup VCenterCursor
    au!
    au BufEnter,WinEnter,WinNew,VimResized *,*.*
            \ let &scrolloff=winheight(win_getid())/2
    augroup END
endif
