-- auto-generated definition
DROP TABLE IF EXISTS SHELL_VAR_SYNTAX;
CREATE TABLE SHELL_VAR_SYNTAX
(
    ID          INTEGER AUTO_INCREMENT,
    "GROUP"     CHARACTER VARYING(16),
    SYNTAX      CHARACTER VARYING(128),
    EXAMPLE_1   CHARACTER VARYING(128),
    EXPECT_1    CHARACTER VARYING(128),
    EXAMPLE_2   CHARACTER VARYING(128),
    EXPECT_2    CHARACTER VARYING(128),
    EXAMPLE_3   CHARACTER VARYING(128),
    EXPECT_3    CHARACTER VARYING(128),
    EXAMPLE_4   CHARACTER VARYING(128),
    EXPECT_4    CHARACTER VARYING(128),
    DESCRIPTION CHARACTER VARYING(256),
    CONSTRAINT SHELL_VAR_SYNTAX_PK
        PRIMARY KEY (ID)
);

COMMENT ON COLUMN SHELL_VAR_SYNTAX."GROUP" IS '分组';

COMMENT ON COLUMN SHELL_VAR_SYNTAX.SYNTAX IS '语法';

COMMENT ON COLUMN SHELL_VAR_SYNTAX.EXAMPLE_1 IS '示例一';

COMMENT ON COLUMN SHELL_VAR_SYNTAX.EXPECT_1 IS '预期输出一';

COMMENT ON COLUMN SHELL_VAR_SYNTAX.EXAMPLE_2 IS '示例二';

COMMENT ON COLUMN SHELL_VAR_SYNTAX.EXPECT_2 IS '预期输出二';

COMMENT ON COLUMN SHELL_VAR_SYNTAX.EXAMPLE_3 IS '示例三';

COMMENT ON COLUMN SHELL_VAR_SYNTAX.EXPECT_3 IS '预期输出三';

COMMENT ON COLUMN SHELL_VAR_SYNTAX.EXAMPLE_4 IS '示例四';

COMMENT ON COLUMN SHELL_VAR_SYNTAX.EXPECT_4 IS '预期输出四';

COMMENT ON COLUMN SHELL_VAR_SYNTAX.DESCRIPTION IS '备注说明';
